name: Lint Code Base

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      # Checkout del código
      - name: Checkout Code
        uses: actions/checkout@v3

      # Configuración de Super-Linter
      - name: Run Super-Linter
        uses: github/super-linter@v5
        env:
          VALIDATE_PYTHON: true  # Habilitar linter para Python
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
